spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://localhost:8081
          predicates:
            - Path=api/accounts/**

        - id: task-service
          uri: lb://localhost:8082
          predicates:
            - Path=api/projects/**

server:
  port: 8083